---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: hello-world-pipeline-
spec:
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
  pipelineSpec:
    params:
      - description: the unique build number
        name: BUILD_ID
        type: string
      - description: the git sha of the tip of the pull request
        name: PULL_PULL_SHA
        type: string
      - description: git url to clone
        name: REPO_URL
        type: string
    workspaces:
      - name: shared-data
    tasks:
      - name: fetch-repo
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-data
        params:
          - name: url
            value: $(params.REPO_URL)
          - name: revision
            value: $(params.PULL_PULL_SHA)

      - name: from-build-pack
        workspaces:
          - name: source
            workspace: shared-data
        resources: {}
        taskSpec:
          workspaces:
            - name: source
          metadata: {}
          stepTemplate:
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 600Mi
            workingDir: /workspace/source
          steps:
            - image: golang:1.15
              name: debug-environment
              resources: {}
              script: |
                #!/bin/sh
                env
            - image: golang:1.15
              name: build-make-linux
              resources: {}
              script: |
                #!/bin/sh
                make linux
  podTemplate: {}
  timeout: 240h0m0s
status: {}
...
