---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: hello-world-pipeline-
spec:
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
  pipelineSpec:
    params:
      - description: the unique build number
        name: BUILD_ID
        type: string
      - description: the git sha of the tip of the pull request
        name: PULL_PULL_SHA
        type: string
      - description: git url to clone
        name: REPO_URL
        type: string
    workspaces:
      - name: shared-data
    tasks:
      - name: fetch-repo
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-data
        params:
          - name: url
            value: $(params.REPO_URL)
          - name: revision
            value: $(params.PULL_PULL_SHA)

      - name: build-application
        runAfter:
          - fetch-repo
        workspaces:
          - name: source
            workspace: shared-data
        resources: {}
        taskSpec:
          workspaces:
            - name: source
          results:
            - name: NEXT-VERSION
              description: The next version for a release.
          metadata: {}
          stepTemplate:
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 600Mi
            workingDir: /workspace/source
          steps:
            - image: golang:1.15
              name: build-make-linux
              resources: {}
              script: |
                #!/bin/sh
                make linux

            - image: gcr.io/jenkinsxio/jx-release-version:2.4.4
              name: get-next-version
              resources: {}
              script: |
                #!/bin/sh
                NEXT_VERSION=$(jx-release-version)
                echo $NEXT_VERSION
                echo $NEXT_VERSION | tee /tekton/results/NEXT-VERSION

      - name: docker-build
        runAfter:
          - build-application
        workspaces:
          - name: source
            workspace: shared-data
        resources: {}
        taskRef:
          name: kaniko
        params:
          - name: IMAGE
            value: garethjevans/test-tekton-client
          - name: EXTRA_ARGS
            value: "--no-push"

  podTemplate: {}
  timeout: 240h0m0s
status: {}
...
