---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
spec:
  params:
    - name: BUILD_ID
      value: ""
    - name: JOB_NAME
      value: ""
    - name: JOB_SPEC
      value: ""
    - name: JOB_TYPE
      value: ""
    - name: PULL_BASE_REF
      value: ""
    - name: PULL_BASE_SHA
      value: ""
    - name: PULL_REFS
      value: ""
    - name: REPO_NAME
      value: ""
    - name: REPO_OWNER
      value: ""
    - name: REPO_URL
      value: ""
  pipelineSpec:
    workspaces:
      - name: shared-data
    tasks:
      - name: fetch-repo
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-data
        params:
          - name: url
            value: $(params.REPO_URL)
          - name: revision
            value: $(params.PULL_BASE_REF)

      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 600Mi
            workingDir: /workspace/source
          steps:
            - image: golang:1.15
              name: debug-environment
              resources: {}
              script: |
                #!/bin/sh
                env
            - image: golang:1.15
              name: build-make-linux
              resources: {}
              script: |
                #!/bin/sh
                make linux
            - image: gcr.io/kaniko-project/executor:debug-v1.3.0
              name: build-container-build
              resources: {}
              script: |
                #!/busybox/sh
                source .jx/variables.sh
                cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
                /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
  podTemplate: {}
  timeout: 240h0m0s
status: {}
...
