---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-asa-code-check
spec:
  params:
    - name: repo_url
    - name: revision
  workspaces:
    - name: source
  tasks:
    - name: fetch
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source
    - name: yaml-lint
      runAfter: [fetch]
      taskRef:
        name: yaml-lint
      params:
        - name: args
          value: ["."]
      workspaces:
        - name: shared-workspace
          workspace: source
    - name: pthon-lint
      runAfter: [fetch]
      taskRef:
        name: pylint
      params:
        - name: path
          value: "tektonasacode/"
        - name: args
          value: ["-r", "y"]
      workspaces:
        - name: source
          workspace: source
    - name: shellcheck
      runAfter: [fetch]
      taskRef:
        name: shellcheck
      params:
        - name: args
          value: ["-s", "bash", "./deploy.sh"]
      workspaces:
        - name: shared-workspace
          workspace: source
